pub mod Errors {
    pub const ZERO_ADDRESS: felt252 = 'UNAUTHORIZED ADDRESS: ZERO';
    pub const ALREADY_REGISTERED: felt252 = 'ADDRESS IS ALREADY REGISTERED';
    pub const USERNAME_TAKEN: felt252 = 'USERNAME ALREADY TAKEN';
    pub const UPDATE_LIMIT: felt252 = 'UPDATE LIMIT REACHED';
    pub const NOT_PLAYER: felt252 = 'NOT A PLAYER';
    pub const CANNOT_CHALLENGE_SELF: felt252 = 'CANNOT CHALLENGE YOURSELF';
    pub const ONLY_OWNER: felt252 = 'CALLER IS NOT THE OWNER';
    pub const INSUFFICIENT_POINTS: felt252 = 'INSUFFICIENT POINTS TO PLAY';

}
